/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menusalon;

/**
 *
 * @author Lenovo
 */
public class TestTNM extends javax.swing.JFrame {

    /**
     * Creates new form TestTNM
     */
    public TestTNM() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new menusalon.TransaksiNonMember();
        transaksi = new javax.swing.JLabel();
        titik2_1 = new javax.swing.JLabel();
        potong_rambut = new javax.swing.JCheckBox();
        creambath = new javax.swing.JCheckBox();
        hair_extention = new javax.swing.JCheckBox();
        rebonding = new javax.swing.JCheckBox();
        hair_spa = new javax.swing.JCheckBox();
        hair_colour = new javax.swing.JCheckBox();
        bleaching = new javax.swing.JCheckBox();
        catok = new javax.swing.JCheckBox();
        pedicure = new javax.swing.JCheckBox();
        menicure = new javax.swing.JCheckBox();
        text_bayar = new javax.swing.JTextField();
        text_th = new javax.swing.JTextField();
        total_harga = new javax.swing.JLabel();
        bayar = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();
        text_kembalian = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        nama = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        total = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transaksi.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        transaksi.setForeground(new java.awt.Color(255, 255, 255));
        transaksi.setText("Transaksi");

        titik2_1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        titik2_1.setForeground(new java.awt.Color(255, 255, 255));
        titik2_1.setText(":");

        potong_rambut.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        potong_rambut.setForeground(new java.awt.Color(255, 255, 255));
        potong_rambut.setText("Potong Rambut @10.000");

        creambath.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        creambath.setForeground(new java.awt.Color(255, 255, 255));
        creambath.setText("Creambath @20.000");

        hair_extention.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        hair_extention.setForeground(new java.awt.Color(255, 255, 255));
        hair_extention.setText("Hair Extention @5.000");

        rebonding.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        rebonding.setForeground(new java.awt.Color(255, 255, 255));
        rebonding.setText("Rebonding @100.000");

        hair_spa.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        hair_spa.setForeground(new java.awt.Color(255, 255, 255));
        hair_spa.setText("Hair Spa @30.000");

        hair_colour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        hair_colour.setForeground(new java.awt.Color(255, 255, 255));
        hair_colour.setText("Hair Colour @50.000");

        bleaching.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        bleaching.setForeground(new java.awt.Color(255, 255, 255));
        bleaching.setText("Bleaching @40.000");

        catok.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        catok.setForeground(new java.awt.Color(255, 255, 255));
        catok.setText("Catok @10.000");

        pedicure.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        pedicure.setForeground(new java.awt.Color(255, 255, 255));
        pedicure.setText("Pedicure @20.000");

        menicure.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        menicure.setForeground(new java.awt.Color(255, 255, 255));
        menicure.setText("Menicure @20.000");

        text_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_bayarActionPerformed(evt);
            }
        });

        total_harga.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        total_harga.setForeground(new java.awt.Color(255, 255, 255));
        total_harga.setText("Total Harga");

        bayar.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        bayar.setForeground(new java.awt.Color(255, 255, 255));
        bayar.setText("Bayar");

        kembalian.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        kembalian.setForeground(new java.awt.Color(255, 255, 255));
        kembalian.setText("Kembalian");

        hitung.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        selesai.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        selesai.setText("Selesai");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        nama.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama");

        total.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titik2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creambath)
                            .addComponent(potong_rambut)
                            .addComponent(hair_extention)
                            .addComponent(hair_spa)
                            .addComponent(rebonding))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hair_colour)
                            .addComponent(bleaching)
                            .addComponent(catok)
                            .addComponent(pedicure)
                            .addComponent(menicure))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(transaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(total_harga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_th, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitung)
                            .addComponent(text_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(selesai, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(transaksi)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titik2_1)
                    .addComponent(nama)
                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potong_rambut)
                    .addComponent(hair_colour))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creambath)
                    .addComponent(bleaching))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hair_extention)
                    .addComponent(catok))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rebonding)
                    .addComponent(pedicure))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hair_spa)
                    .addComponent(menicure))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_harga)
                    .addComponent(text_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bayar)
                    .addComponent(text_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalian))
                        .addGap(18, 18, 18)
                        .addComponent(hitung))
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(selesai)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_bayarActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        TestLogin a = new TestLogin();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_selesaiActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        totalharga();
    }//GEN-LAST:event_totalActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        kembalian();
    }//GEN-LAST:event_hitungActionPerformed

    public void totalharga(){
        int total = 0;
        if(potong_rambut.isSelected()){
            int hargapotong_rambut = 10000;
            total=total+hargapotong_rambut;
        }
        if(creambath.isSelected()){
            int hargacreambath = 20000;
            total=total+hargacreambath;
        }
        if(hair_extention.isSelected()){
            int hargahair_extention = 5000;
            total=total+hargahair_extention;
        }
        if(rebonding.isSelected()){
            int hargarebonding = 100000;
            total=total+hargarebonding;
        }
        if(hair_spa.isSelected()){
            int hargahair_spa = 30000;
            total=total+hargahair_spa;
        }
        if(hair_colour.isSelected()){
            int hargahair_colour = 50000;
            total=total+hargahair_colour;
        }
        if(bleaching.isSelected()){
            int hargableaching = 40000;
            total=total+hargableaching;
        }
        if(catok.isSelected()){
            int hargacatok = 10000;
            total=total+hargacatok;
        }
        if(pedicure.isSelected()){
            int hargapedicure = 20000;
            total=total+hargapedicure;
        }
        if(menicure.isSelected()){
            int hargamenicure = 20000;
            total=total+hargamenicure;
        }
        text_th.setText(""+total);
    }
    
    public void kembalian(){
        int a, b, c;
        a = Integer.parseInt(text_bayar.getText());
        b = Integer.parseInt(text_th.getText());
        c = (a-b);
        text_kembalian.setText(String.valueOf(c));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTNM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTNM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTNM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTNM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestTNM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bayar;
    private javax.swing.JCheckBox bleaching;
    private javax.swing.JCheckBox catok;
    private javax.swing.JCheckBox creambath;
    private javax.swing.JCheckBox hair_colour;
    private javax.swing.JCheckBox hair_extention;
    private javax.swing.JCheckBox hair_spa;
    private javax.swing.JButton hitung;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kembalian;
    private javax.swing.JCheckBox menicure;
    private javax.swing.JLabel nama;
    private javax.swing.JCheckBox pedicure;
    private javax.swing.JCheckBox potong_rambut;
    private javax.swing.JCheckBox rebonding;
    private javax.swing.JButton selesai;
    private javax.swing.JTextField text_bayar;
    private javax.swing.JTextField text_kembalian;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_th;
    private javax.swing.JLabel titik2_1;
    private javax.swing.JButton total;
    private javax.swing.JLabel total_harga;
    private javax.swing.JLabel transaksi;
    // End of variables declaration//GEN-END:variables
}
