/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menusalon;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class TestAkun extends javax.swing.JFrame {

    /**
     * Creates new form TestAkun
     */
    Statement stm;
    ResultSet rs;
    DefaultTableModel tb = new DefaultTableModel();
    public TestAkun() {
        initComponents();
        setLocationRelativeTo(this);
        db_salon kon = new db_salon();
        kon.getKoneksi();
        stm = kon.stm;
            table.setModel(tb);
            tb.addColumn("Id Number");
            tb.addColumn("Nama");
            tb.addColumn("No. Telp");
            tb.addColumn("Alamat");
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new menusalon.Akun();
        AKUN = new javax.swing.JLabel();
        id_number = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        no_telp = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        titik2_1 = new javax.swing.JLabel();
        titik2_2 = new javax.swing.JLabel();
        titik2_3 = new javax.swing.JLabel();
        titik2_4 = new javax.swing.JLabel();
        text_Id = new javax.swing.JTextField();
        text_nm = new javax.swing.JTextField();
        text_telp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_almt = new javax.swing.JTextArea();
        selesai = new javax.swing.JButton();
        simpan = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel1.setText("Akun");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AKUN.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        AKUN.setText("Akun");

        id_number.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        id_number.setText("Id Number");

        nama.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        nama.setText("Nama");

        no_telp.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        no_telp.setText("No. Telp");

        alamat.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        alamat.setText("Alamat");

        titik2_1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        titik2_1.setText(":");

        titik2_2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        titik2_2.setText(":");

        titik2_3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        titik2_3.setText(":");

        titik2_4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        titik2_4.setText(":");

        text_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_IdActionPerformed(evt);
            }
        });

        table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Number", "Nama", "No. Telp", "Alamat"
            }
        ));
        table.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(table);

        text_almt.setColumns(20);
        text_almt.setRows(5);
        jScrollPane2.setViewportView(text_almt);

        selesai.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        selesai.setText("Kembali");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });

        simpan.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AKUN)
                .addGap(314, 314, 314))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(no_telp)
                            .addComponent(alamat))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id_number)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titik2_4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titik2_3)
                        .addGap(18, 18, 18)
                        .addComponent(text_telp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titik2_2)
                        .addGap(18, 18, 18)
                        .addComponent(text_nm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titik2_1)
                        .addGap(18, 18, 18)
                        .addComponent(text_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(AKUN)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_number)
                    .addComponent(titik2_1)
                    .addComponent(text_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(titik2_2)
                    .addComponent(text_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_telp)
                    .addComponent(titik2_3)
                    .addComponent(text_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alamat)
                        .addComponent(titik2_4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_IdActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        TestMember a = new TestMember();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_selesaiActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        simpan();
    }//GEN-LAST:event_simpanActionPerformed

    public void simpan(){
        try{
            String i = text_Id.getText();
            String n = text_nm.getText();
            String t = text_telp.getText();
            String a = text_almt.getText();
            String sql = "Insert into data_member values ('"+ i +"','"+ n +"','"+ t +"','"+ a +"')";
            stm.execute(sql);
            tampil();
        }catch (SQLException ex){
            System.out.println(ex);
        }
    }
    
    public void tampil(){
        String sql = "Select * from data_member";
        try{
            tb.getDataVector().removeAllElements();
            tb.fireTableDataChanged();
            rs = stm.executeQuery(sql);
            while (rs.next()){
                Object[] obj = new Object[4];
                obj[0] = rs.getString("Id_Number");
                obj[1] = rs.getString("Nama");
                obj[2] = rs.getString("No_Telp");
                obj[3] = rs.getString("Alamat");
                tb.addRow(obj);
            }
        }catch (SQLException ex){
                System.out.println(ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AKUN;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel id_number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel no_telp;
    private javax.swing.JButton selesai;
    private javax.swing.JButton simpan;
    private javax.swing.JTable table;
    private javax.swing.JTextField text_Id;
    private javax.swing.JTextArea text_almt;
    private javax.swing.JTextField text_nm;
    private javax.swing.JTextField text_telp;
    private javax.swing.JLabel titik2_1;
    private javax.swing.JLabel titik2_2;
    private javax.swing.JLabel titik2_3;
    private javax.swing.JLabel titik2_4;
    // End of variables declaration//GEN-END:variables
}
